language: elixir
elixir:
  - 1.11.2
otp_release:
  - 23.0
services:
    - postgresql
addons:
    postgresql: '9.6'

before_script:
  - psql -c "ALTER USER postgres PASSWORD 'postgres';" -U postgres
  - psql -c "ALTER USER postgres WITH SUPERUSER;"

env:
  - MIX_ENV=test
script:
  - mix do deps.get, test && mix compile --warnings-as-errors && mix coveralls.travis

